---

- import_tasks: redhat.yml
  when: (ansible_os_family | lower == 'redhat') and not python3_miniconda

- import_tasks: debian.yml
  when: (ansible_os_family | lower == 'debian') and not python3_miniconda

- import_tasks: conda.yml
  when: and not python3_miniconda

- name: python3 venv | create python virtualenv wrapper
  become: true
  template:
    dest: /usr/local/bin/ome-python3-virtualenv
    src: ome-python3-virtualenv.sh
    mode: 'u=rwx,g=rx,o=rx'
